import { useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { useAuth } from "@/contexts/AuthContext";
import { useToast } from "@/hooks/use-toast";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ShoppingCart, Printer, History } from "lucide-react";

const Cashier = () => {
  const navigate = useNavigate();
  const { user } = useAuth();
  const { toast } = useToast();

  useEffect(() => {
    if (user?.role !== "CASHIER") {
      toast({
        title: "Access Denied",
        description: "You don't have permission to access this page.",
        variant: "destructive",
      });
      navigate("/");
    }
  }, [user, navigate, toast]);

  const handleNewSale = () => {
    navigate("/sales/new");
  };

  const handleViewSales = () => {
    navigate("/sales");
  };

  const handlePrintReport = async () => {
    try {
      // Create print content for daily report
      const printContent = `
        <html>
          <head>
            <title>Daily Sales Report</title>
            <style>
              body { font-family: system-ui; padding: 20px; }
              .header { text-align: center; margin-bottom: 20px; }
              .date { margin-bottom: 15px; }
              .total { margin-top: 15px; font-weight: bold; }
            </style>
          </head>
          <body>
            <div class="header">
              <h2>Daily Sales Report</h2>
              <div class="date">${new Date().toLocaleDateString()}</div>
            </div>
            <div class="total">
              Generated by: ${user?.name}
            </div>
          </body>
        </html>
      `;

      // Create a hidden iframe for printing
      const iframe = document.createElement('iframe');
      iframe.style.display = 'none';
      document.body.appendChild(iframe);
      
      iframe.contentDocument?.write(printContent);
      iframe.contentDocument?.close();

      try {
        await iframe.contentWindow?.print();
        toast({
          title: "Success",
          description: "Report printed successfully",
        });
      } catch (error) {
        throw new Error("Printing failed");
      } finally {
        document.body.removeChild(iframe);
      }
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to print report. Please check your printer connection.",
        variant: "destructive",
      });
    }
  };

  if (user?.role !== "CASHIER") {
    return null;
  }

  return (
    <div className="container mx-auto p-6">
      <h1 className="text-2xl font-bold mb-6">Cashier Dashboard</h1>
      <div className="grid gap-6 md:grid-cols-3">
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <ShoppingCart className="h-5 w-5" />
              New Sale
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-muted-foreground mb-4">
              Create a new sale transaction
            </p>
            <Button onClick={handleNewSale} className="w-full">
              Start New Sale
            </Button>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <History className="h-5 w-5" />
              View Sales
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-muted-foreground mb-4">
              View sales history and details
            </p>
            <Button onClick={handleViewSales} variant="outline" className="w-full">
              View History
            </Button>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Printer className="h-5 w-5" />
              Print Report
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-muted-foreground mb-4">
              Print daily sales report
            </p>
            <Button onClick={handlePrintReport} variant="outline" className="w-full">
              Print Report
            </Button>
          </CardContent>
        </Card>
      </div>
    </div>
  );
};

export default Cashier;