import React, { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Download, FileSpreadsheet, FileText, Printer } from 'lucide-react';
import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { exportToCSV } from '@/lib/exportUtils';
import { useAuth } from '@/contexts/AuthContext';
import { toast } from 'sonner';
import type { ReportFilters } from '@/hooks/reports/useReportFilters';

export interface ExportColumn {
    key: string;
    header: string;
    formatter?: (value: any) => string;
}

interface ReportExportPanelProps {
    reportName: string;
    data: any[];
    columns: ExportColumn[];
    filters?: ReportFilters;
    formats?: ('csv' | 'excel' | 'pdf' | 'print')[];
    onExport?: (format: string) => void;
    className?: string;
}

/**
 * Unified export interface for all reports.
 * Supports CSV, Excel, PDF, and Print with metadata.
 */
export const ReportExportPanel: React.FC<ReportExportPanelProps> = ({
    reportName,
    data,
    columns,
    filters,
    formats = ['csv', 'print'],
    onExport,
    className = ''
}) => {
    const { user } = useAuth();
    const [isExporting, setIsExporting] = useState(false);

    const generateMetadata = () => {
        const metadata: Record<string, string> = {
            'Report': reportName,
            'Generated By': user?.name || user?.username || 'Unknown',
            'Generated At': new Date().toLocaleString(),
        };

        if (filters?.startDate && filters?.endDate) {
            metadata['Date Range'] = `${new Date(filters.startDate).toLocaleDateString()} - ${new Date(filters.endDate).toLocaleDateString()}`;
        }

        if (filters?.branchIds && filters.branchIds[0] !== 'all') {
            metadata['Branch'] = filters.branchIds.join(', ');
        }

        return metadata;
    };

    const handleCSVExport = () => {
        try {
            setIsExporting(true);

            // Prepare data with formatted values
            const exportData = data.map(row => {
                const formattedRow: Record<string, any> = {};
                columns.forEach(col => {
                    const value = row[col.key];
                    formattedRow[col.key] = col.formatter ? col.formatter(value) : value;
                });
                return formattedRow;
            });

            // Create headers mapping
            const headers: Record<string, string> = {};
            columns.forEach(col => {
                headers[col.key] = col.header;
            });

            // Add metadata as comment rows (CSV doesn't support metadata natively)
            const metadata = generateMetadata();
            const metadataRows = Object.entries(metadata).map(([key, value]) =>
                `# ${key}: ${value}`
            ).join('\n');

            // Export with metadata in filename
            const filename = `${reportName.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}`;
            exportToCSV(exportData, filename, headers);

            toast.success('Report exported successfully');
            onExport?.('csv');
        } catch (error) {
            console.error('Export error:', error);
            toast.error('Failed to export report');
        } finally {
            setIsExporting(false);
        }
    };

    const handlePrint = () => {
        try {
            setIsExporting(true);

            const metadata = generateMetadata();
            const metadataHTML = Object.entries(metadata)
                .map(([key, value]) => `<p><strong>${key}:</strong> ${value}</p>`)
                .join('');

            const tableHTML = `
        <table>
          <thead>
            <tr>
              ${columns.map(col => `<th>${col.header}</th>`).join('')}
            </tr>
          </thead>
          <tbody>
            ${data.map(row => `
              <tr>
                ${columns.map(col => {
                const value = row[col.key];
                const formatted = col.formatter ? col.formatter(value) : value;
                return `<td>${formatted || ''}</td>`;
            }).join('')}
              </tr>
            `).join('')}
          </tbody>
        </table>
      `;

            const printContent = `
        <html>
          <head>
            <title>${reportName}</title>
            <style>
              @media print {
                body { font-family: system-ui, -apple-system, sans-serif; padding: 20px; }
                h1 { text-align: center; margin-bottom: 10px; }
                .metadata { margin-bottom: 20px; padding: 10px; background: #f5f5f5; }
                .metadata p { margin: 5px 0; font-size: 12px; }
                table { width: 100%; border-collapse: collapse; margin-top: 20px; }
                th, td { border: 1px solid #ddd; padding: 8px; text-align: left; font-size: 11px; }
                th { background-color: #f5f5f5; font-weight: bold; }
                @page { margin: 0.5cm; }
              }
            </style>
          </head>
          <body>
            <h1>${reportName}</h1>
            <div class="metadata">
              ${metadataHTML}
            </div>
            ${tableHTML}
          </body>
        </html>
      `;

            const printWindow = window.open('', '_blank');
            if (printWindow) {
                printWindow.document.write(printContent);
                printWindow.document.close();
                printWindow.focus();
                printWindow.print();
                printWindow.close();
            }

            toast.success('Print preview opened');
            onExport?.('print');
        } catch (error) {
            console.error('Print error:', error);
            toast.error('Failed to open print preview');
        } finally {
            setIsExporting(false);
        }
    };

    const handleExcelExport = () => {
        toast.info('Excel export coming soon');
        // TODO: Implement Excel export with proper formatting
    };

    const handlePDFExport = () => {
        toast.info('PDF export coming soon');
        // TODO: Implement PDF export with proper formatting
    };

    if (data.length === 0) {
        return null;
    }

    return (
        <Card className={className}>
            <CardHeader>
                <CardTitle className="text-lg">Export Report</CardTitle>
            </CardHeader>
            <CardContent>
                <div className="flex flex-wrap gap-2">
                    {formats.includes('csv') && (
                        <Button
                            variant="outline"
                            size="sm"
                            onClick={handleCSVExport}
                            disabled={isExporting}
                        >
                            <FileSpreadsheet className="mr-2 h-4 w-4" />
                            Export CSV
                        </Button>
                    )}

                    {formats.includes('excel') && (
                        <Button
                            variant="outline"
                            size="sm"
                            onClick={handleExcelExport}
                            disabled={isExporting}
                        >
                            <FileSpreadsheet className="mr-2 h-4 w-4" />
                            Export Excel
                        </Button>
                    )}

                    {formats.includes('pdf') && (
                        <Button
                            variant="outline"
                            size="sm"
                            onClick={handlePDFExport}
                            disabled={isExporting}
                        >
                            <FileText className="mr-2 h-4 w-4" />
                            Export PDF
                        </Button>
                    )}

                    {formats.includes('print') && (
                        <Button
                            variant="outline"
                            size="sm"
                            onClick={handlePrint}
                            disabled={isExporting}
                        >
                            <Printer className="mr-2 h-4 w-4" />
                            Print
                        </Button>
                    )}

                    {formats.length > 2 && (
                        <DropdownMenu>
                            <DropdownMenuTrigger asChild>
                                <Button variant="outline" size="sm" disabled={isExporting}>
                                    <Download className="mr-2 h-4 w-4" />
                                    More Options
                                </Button>
                            </DropdownMenuTrigger>
                            <DropdownMenuContent>
                                {formats.includes('csv') && (
                                    <DropdownMenuItem onClick={handleCSVExport}>
                                        <FileSpreadsheet className="mr-2 h-4 w-4" />
                                        CSV
                                    </DropdownMenuItem>
                                )}
                                {formats.includes('excel') && (
                                    <DropdownMenuItem onClick={handleExcelExport}>
                                        <FileSpreadsheet className="mr-2 h-4 w-4" />
                                        Excel
                                    </DropdownMenuItem>
                                )}
                                {formats.includes('pdf') && (
                                    <DropdownMenuItem onClick={handlePDFExport}>
                                        <FileText className="mr-2 h-4 w-4" />
                                        PDF
                                    </DropdownMenuItem>
                                )}
                                {formats.includes('print') && (
                                    <DropdownMenuItem onClick={handlePrint}>
                                        <Printer className="mr-2 h-4 w-4" />
                                        Print
                                    </DropdownMenuItem>
                                )}
                            </DropdownMenuContent>
                        </DropdownMenu>
                    )}
                </div>

                <p className="text-xs text-muted-foreground mt-3">
                    Exports include metadata: date range, branch, and generation timestamp
                </p>
            </CardContent>
        </Card>
    );
};
